// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCROqd3jHHsFFE1u_CA6c2M9fjZIHslxEU',
    appId: '1:955651766880:web:077c7983bf25841363a105',
    messagingSenderId: '955651766880',
    projectId: 'fir-authentication-315f4',
    authDomain: 'fir-authentication-315f4.firebaseapp.com',
    storageBucket: 'fir-authentication-315f4.firebasestorage.app',
    measurementId: 'G-J10KHZBPR4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGahWo1blIrBqYrLhrQXVlTRi8azy1mYg',
    appId: '1:955651766880:android:7459e83e7ae154b163a105',
    messagingSenderId: '955651766880',
    projectId: 'fir-authentication-315f4',
    storageBucket: 'fir-authentication-315f4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4fEkUsiU425dkBTvGb1ZXRw06Ynr8yOI',
    appId: '1:955651766880:ios:62951fc1654ffa1663a105',
    messagingSenderId: '955651766880',
    projectId: 'fir-authentication-315f4',
    storageBucket: 'fir-authentication-315f4.firebasestorage.app',
    iosBundleId: 'com.example.authProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4fEkUsiU425dkBTvGb1ZXRw06Ynr8yOI',
    appId: '1:955651766880:ios:62951fc1654ffa1663a105',
    messagingSenderId: '955651766880',
    projectId: 'fir-authentication-315f4',
    storageBucket: 'fir-authentication-315f4.firebasestorage.app',
    iosBundleId: 'com.example.authProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCROqd3jHHsFFE1u_CA6c2M9fjZIHslxEU',
    appId: '1:955651766880:web:9d46ae74c2ff3f2363a105',
    messagingSenderId: '955651766880',
    projectId: 'fir-authentication-315f4',
    authDomain: 'fir-authentication-315f4.firebaseapp.com',
    storageBucket: 'fir-authentication-315f4.firebasestorage.app',
    measurementId: 'G-DT1HXGE6WJ',
  );
}
